// <auto-generated />
namespace Blog.Datos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Categorias_QuitarRelacionConBlog : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Categorias_QuitarRelacionConBlog));
        
        string IMigrationMetadata.Id
        {
            get { return "201901232039004_Categorias_QuitarRelacionConBlog"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
